# Generated by Django 3.2.4 on 2021-06-18 19:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.UUID)),
                ('name', models.CharField(max_length=255, null=True)),
                ('department', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'doctors',
            },
        ),
        migrations.CreateModel(
            name='RegistryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.UUID)),
                ('region', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('street', models.CharField(max_length=255, null=True)),
                ('house', models.CharField(max_length=255, null=True)),
                ('apartment', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'registry_address',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.UUID)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('sex', models.BooleanField(null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('oms', models.CharField(max_length=255, null=True)),
                ('insurance', models.CharField(max_length=255, null=True)),
                ('passport', models.CharField(max_length=255, null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='monitoring_system.doctor')),
                ('registry_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='monitoring_system.registryaddress')),
            ],
            options={
                'db_table': 'patients',
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.UUID)),
                ('date', models.DateField(null=True)),
                ('upper_point', models.IntegerField(null=True)),
                ('lower_point', models.IntegerField(null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='monitoring_system.patient')),
            ],
            options={
                'db_table': 'measurements',
            },
        ),
    ]
