# Generated by Django 3.2.4 on 2021-06-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_system', '0002_auto_20210618_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='registry_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
