# Generated by Django 3.2.4 on 2021-06-18 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_system', '0003_auto_20210618_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='doctor',
            new_name='doctor_id',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='registry_address',
            new_name='registry_address_id',
        ),
    ]
