# Generated by Django 3.2.4 on 2021-06-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_system', '0004_auto_20210618_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='patronymic',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
