# Generated by Django 3.2.4 on 2021-06-19 07:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_system', '0006_auto_20210618_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.UUID)),
                ('login', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'auth_doctors',
            },
        ),
    ]
