# Generated by Django 3.2.4 on 2021-06-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_system', '0007_authdoctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='pulse',
            field=models.IntegerField(null=True),
        ),
    ]
