# Generated by Django 3.2.4 on 2021-06-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_system', '0008_measurement_pulse'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='snils',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
