# Generated by Django 3.2.4 on 2021-06-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_system', '0012_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='patient_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='medicine_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
