# Generated by Django 3.2.4 on 2021-06-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_system', '0013_auto_20210619_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='activity',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
