# Generated by Django 3.2.4 on 2021-06-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_system', '0014_measurement_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.BooleanField(null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('date_from', models.DateField(null=True)),
                ('date_to', models.DateField(null=True)),
                ('patient_id', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'prescriptions',
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='prescription_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
