# Generated by Django 3.2.4 on 2021-06-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_system', '0015_auto_20210619_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
