# Generated by Django 3.2.4 on 2021-06-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_system', '0016_alter_prescription_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='type',
            field=models.IntegerField(null=True),
        ),
    ]
